### ISSUE TITLE
Make a short talk on Stackoverflow TV

### ISSUE THREAD

**Issue by tburny** [headissue/cache2k#5]
Stackoverflow offers short talks for poeple who want to decide if a certain tool is suitable for them:
http://meta.stackoverflow.com/questions/270574/an-experiment-stack-overflow-tv

I want to suggest this for cache2k, as  soon as the SO-tag exists.

**Comment by cruftex** [comment]
> The episodes will be shot at the Stack office in New York City

Good idea, but I have no plans to travel to New York....
